### ISSUE TITLE
Testing with protein leads to TypeError

### ISSUE THREAD

**Issue by noamteyssier** [daquang/YAMDA#8]
tried a test run with run_em on protein sequences and resulted in a TypeError

full trace with input :
![errorcode](https://user-images.githubusercontent.com/22600644/50239258-8beb7900-0376-11e9-8e47-488841170fdc.png)

**Comment by daquang** [comment]
I pushed an update. Changing line 152 to convert the number to cpu. Can you check if this update works?

Also, I've never done motif discovery with proteins before, so I'm very interested in your results.

**Comment by noamteyssier** [comment]
So I was able to get it running by editing lines 153, 320, 330, and 342 in Mixture.py by converting to cpu. 

One last update is in utils.py in the print statement of the PPM to make it relative to the number of letters in the alphabet and not just the 4 DNA sequences. 

I'm just back from the holidays so I will be comparing the results I receive with YAMDA with those of MEME and keep you updated!
